-- liquibase formatted sql

-- changeset laterna:1

CREATE TABLE user_settings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    theme            VARCHAR(20)                                    NOT NULL,
    created_at       TIMESTAMPTZ                                    NOT NULL,
    last_modified_at TIMESTAMPTZ                                    NOT NULL
);
-- rollback DROP TABLE IF EXISTS user_settings;
