-- liquibase formatted sql

-- changeset laterna:1

CREATE TABLE p2p_settings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_user_id   BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    target_user_id   BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    is_muted         BOOLEAN                                        NOT NULL DEFAULT FALSE,
    volume_level     INTEGER                                        NOT NULL DEFAULT 100,
    created_at       TIMESTAMPTZ                                    NOT NULL,
    last_modified_at TIMESTAMPTZ                                    NOT NULL
);
-- rollback DROP TABLE IF EXISTS p2p_settings;
