-- liquibase formatted sql

-- changeset laterna:1

CREATE TABLE hub_mutes
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id           BIGINT REFERENCES hubs (id) ON DELETE CASCADE  NOT NULL,
    user_id          BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    expires_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ                                    NOT NULL,
    last_modified_at TIMESTAMPTZ                                    NOT NULL
);
-- rollback DROP TABLE IF EXISTS hub_mutes;
