-- liquibase formatted sql

-- changeset laterna:1

CREATE TABLE hidden_messages
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT REFERENCES users (id) ON DELETE CASCADE    NOT NULL,
    message_id       BIGINT REFERENCES messages (id) ON DELETE CASCADE NOT NULL,
    created_at       TIMESTAMPTZ                                       NOT NULL,
    last_modified_at TIMESTAMPTZ                                       NOT NULL
);
-- rollback DROP TABLE IF EXISTS hidden_messages;
