-- liquibase formatted sql

-- changeset laterna:1

CREATE TABLE media_sign
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    media_id         BIGINT REFERENCES media (id) ON DELETE CASCADE NOT NULL,
    sign             VARCHAR(256)                                   NOT NULL,
    expires_At       TIMESTAMPTZ                                    NOT NULL,
    created_at       TIMESTAMPTZ                                    NOT NULL,
    last_modified_at TIMESTAMPTZ                                    NOT NULL
);
-- rollback DROP TABLE IF EXISTS hidden_messages;
