spring:
  application:
    name: flux

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/flux?reWriteBatchedInserts=true
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC

  data:
    redis:
      password: redis
      host: redis
      port: 6379

app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:63342

jwt:
  secret: MTNwVjZlWUQ1OU1Uc2szK2NUdnE2WjZSWVNCWFlBbEFHaTAvMjkyRFk5cVR1TzYxbFd6VDVIYVRXUEtQUnpITFg0ajRiKyt3OFl3WmhEWEhnUkk0M3FPQW9TK24zc093UXgwTm1NNmtwUFlkT094aXA1dFZMbnMzbmU5amZqRENYdzJiVUdHLytBV25xeDN6YkNld3RCM0FlQ2wyYitZbFEybTg4MTVZMHZ1L0lLdkg0Q0RLR0NZdXF0d0NuTVc4VUNtMjJTU2RlMjc4bnlaNVNMQXl3TzE2Z1h6dnl4TE11Ni9tdXFCWnM0WXZSNGNhZk5sWE5EQnBxU21KMGI1WmFhNUhoWjJFaXByRGFlSDNYWm0weVNUY2Qxa05WdERHbjdPT2dWRk9GVWxoUzNtOEFVZkhiaURWVTF5Qm9id2N5Qjl4cHMvNDRsQVJkMzJnRENoYmFQcHdsUXZ0ZkVYSW5maXBLYXVibFpFPQ==
  access:
    expiration: 8640000
  refresh:
    expiration: 8640000