services:
  database:
    container_name: cm-postgres
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=flux
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-network

  redis:
    container_name: cm-redis
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass redis --appendonly yes --notify-keyspace-events Ex
    networks:
      - spring-network

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: cm-kafka
    volumes:
      - kafka-data:/kafka/data
    ports:
      - "9092:9092"
    environment:
      # Основные настройки KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # Настройка кворума для одного узла (1@kafka:29093)
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'

      # Настройка слушателей
      # CONTROLLER - для внутреннего управления кластером
      # PLAINTEXT - для клиентских подключений
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # Дополнительные настройки для режима разработки
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      # Важные настройки для KRaft
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # Отключаем ZooKeeper
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: cm-schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_PROTOBUF_SUPPORTED: "true"
networks:
  spring-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  kafka-data: