services:
  database:
    container_name: ca-postgres
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=connexe-auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-network


networks:
  spring-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  kafka-data: